config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'home#index'

  resources :questions do
  	resources :answers, only: [:create]
  	member do
  		post 'follow_topic', to: 'follower#follow_topic', as: :follow_topic
  		post 'follow_user', to: 'follower#follow_user', as: :follow_user

  	end
  end

  resources :topics

end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	belongs_to :question

	validate_presence_of :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	belongs_to :topic
	has_many :answers, dependent: :destroy

	validates_presence_of :name
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :topic_followers
	has_many :users, through: :topic_followers
	has_many :questions, dependent: :destroy

	validates_presence_of :name
end

app/models/topic_follower.rb
class TopicFollower < ApplicationRecord
	belongs_to :user
	belongs_to :topic

	validates :topic, uniqueness: {scope: :user, message: "Already Following"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
	has_many :answers, dependent: :destroy
	has_many :user_followers
	has_many :following, through: :user_followers, source: :follower

	has_many :topic_followers
	has_many :topics, through: :topic_followers

end

app/models/user_follower.rb
class UserFollower < ApplicationRecord
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    answer = question.answers.new(answers_params.merge(user_id: current_user.id))
    if answer.save
      redirect_to question_path(question), notice: 'Answer created sucessfully'
    else
      redirect_to question_path(question), notice: 'Answer not created'
    end
  end

  private
  def answers_params
    params.require(:answer).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		'/'
	end

	def after_sign_out_path_for(resource)
		'/users/sign_in'
	end
	
end

app/controllers/follower_controller.rb
class FollowerController < ApplicationController
	before_action :find_user, only: :follow_user
	before_action :find_topic_id, only: :follow_topic

	def follow_user
		if current_user.present?
			unless validate_following_user?
				follower = @user.user_followers.create(follower_id: current_user.id)
				notice = follower.errors.present? ? follower.errors.full_messages.join(', ') : 'Followed sucessfully'
			else
				notice = 'Can not follow your self'
			end
		else
			notice = "you have to log_in first"
		end
		redirect_to '/', notice: notice
	end

	def follow_topic
		follower = current_user.topic_followers.create(topic_id: @topic_id) if current_user.present?
		notice = "you have to log_in first"
		notice = follower.errors.present? ? follower.errors.full_messages.join(', ') : 'Topic followed sucessfully' if follower.present?
		redirect_to '/', notice: notice
	end

	private
	
	def find_user
		@user = Question.find(params[:id]).user
	end

	def find_topic_id
		@topic_id = Question.find(params[:id]).topic_id
	end

	def validate_following_user?
		current_user.id == @user.id
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@questions = Question.all
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index 
		if current_user.present?
			@questions = current_user.questions 
		else
			notice = "you have to log_in first"
		end
	end

	def new
		@question = Question.new
	end

	def create
		if current_user.present?
			question = current_user.questions.new(question_params)
			if question.save
				redirect_to question_path(question), notice: 'Question created sucessfully'
			else
				redirect_to '/', notice: 'Question not created'
			end
		else
			redirect_to '/', notice: 'you have to log_in first'
		end
	end


	def show
		@question = Question.find(params[:id])
		@answers = @question.answers
	end


	private
	def question_params
		params.require(:question).permit(:name,:topic_id)
	end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	def new
		@topic = Topic.new
	end

	def create
		if current_user.present?
			topic = Topic.new(topic_params)
			if topic.save
				redirect_to '/', notice: 'Topic created sucessfully'
			else
				redirect_to '/', notice: 'Topic not created'
			end
		else
			redirect_to '/', notice: 'You have to log in first'
			
		end
	end

	private
	def topic_params
		params.require(:topic).permit(:name)
	end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/follower_helper.rb
module FollowerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/home/index.html.erb
<h3>HOME PAGE</h3>

<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>
   <%@errors ||= []%>

<% if @errors.any? %>
  <% @errors.full_messages.each do |message| %>
  		<li><%= message %></li>
  <% end %>
<% end %>

<% @questions.each do |question| %>
	<p> Question:- <%= link_to "#{question.name}", question_url(question.id), class: 'question' %></p>
	
	<p>Topic:- <%=question.topic.name %> <%= button_to "follow", "#{request.base_url}/questions/#{question.id}/follow_topic", method: :post %></p>

	<p> Created By:- <%= question.user.email%>  <%= button_to "follow_user", follow_user_question_url(question.id), method: :post %></p><br>

<% end %>

<%= link_to 'create question', new_question_path %>
<%= link_to 'create topic', new_topic_path %>


<br>
<% unless current_user.present? %>
    <%= button_to 'sign_in', new_user_session_url %>
  <%else%>
    <%= button_to 'sign_out', destroy_user_session_url, method: :delete %>
  <%end%>

app/views/questions/new.html.erb
<h3> Create Question </h3>
<%=form_for @question do |f| %>
	<%=f.label 'Select Topic' %>
	<%=f.select :topic_id, options_for_select(Topic.all.map{|t|[t.name,t.id]}) %>
	<%=f.label "Question"%>
	<%=f.text_field :name %>
	<button type = "submit" class = "btn btn-primary">Submit</button> 
<% end %>
<%=link_to "Home", '/'%>

app/views/questions/show.html.erb
<h3> <%=@question.name %> </h3>

<% @answers.each do |answer| %>
	<p><%=answer.name%></p>
<%end%>

<h3>Submit Answer</h3>
<%= form_for :answer, url: question_answers_path(@question) do |f| %>
	<%=f.text_area :name %>
	<button type = "submit" class = "btn btn-primary">Submit</button> 
<% end %>

<%=link_to "Home", '/'%>

app/views/topics/new.html.erb
<h3>Create Topic</h3>
<%=form_for @topic do |form| %>
	<%=form.label 'Topic'%>
	<%=form.text_field :name %> <br>
	<button type = "submit" class = "btn btn-primary">Submit</button> 
<%end%>

<%=link_to "Home", '/'%>